export enum EnvVars {
    // logger settings
    LOG_LEVEL="LOG_LEVEL",

    // server settings
    LISTEN_PORT="LISTEN_PORT",

    // hashing
    HASH_SECRET="HASH_SECRET",

    // ws
    WS_MESSAGE_PERSISTENCE_ENGINE="WS_MESSAGE_PERSISTENCE_ENGINE",
    WS_MESSAGE_DISTRIBUTION_ENGINE="WS_MESSAGE_DISTRIBUTION_ENGINE",
    WS_CONN_PERSISTENCE_ENGINE="WS_CONN_PERSISTENCE_ENGINE",

    // redis settings
    REDIS_PORT="REDIS_PORT",
    REDIS_HOST="REDIS_HOST",
    REDIS_PASSWORD="REDIS_PASSWORD",
    REDIS_CONNECT_TIMEOUT="REDIS_CONNECT_TIMEOUT",
    REDIS_AUTO_RESUBSCRIBE="REDIS_AUTO_RESUBSCRIBE",
    CHAT_MESSAGES_DB="CHAT_MESSAGES_DB",
    CHAT_CONN_DB="CHAT_CONN_DB",

    // kafka
    KAFKA_BROKERS="KAFKA_BROKERS",

    // cassandra
    CASSANDRA_HOSTS="CASSANDRA_HOSTS",
    CASSANDRA_KEYSPACE="CASSANDRA_KEYSPACE"
}